swagger: "2.0"
info:
  version: 1.0.0
  title: fastcampus-api-server
  description: fastcampus-api-server
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Balance
    description: Simple Balance Transfer Example
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

  move:
    required:
      - from
      - to
      - amount
    properties:
      from:
        type: string
      to:
        type: string
      amount:
        type: integer

  user:
    required:
      - name
      - balance
    properties:
      name:
        type: string
      balance:
        type: integer

paths:
  /balance/{id}:
    get:
      tags:
        - Balance
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to retrieve currently balance
          type: string
      description: Get User Balance
      responses:
        200:
          description: Returns User's Currently Balance

  /balance/user:
    post:
      tags:
        - Balance
      Summary: Add the new user
      parameters:
        - name: id
          in: body
          required: true
          schema:
            $ref: "#/definitions/user"
      description: The id of the user to be added
      responses:
        200:
          description: Returns User's Current Balance

  /balance:
    post:
      tags:
        - Balance
      parameters:
        - name: move balance request
          in: body
          description: The id of the user to retrieve currently balance
          required: true
          schema:
            $ref: "#/definitions/move"
      description: Get User Balance
      responses:
        200:
          description: Returns User's Currently Balance

  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
